# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Honest rpart Estimates
#'
#' Computes honest estimates for a rpart object.
#'
#' @param unique_leaves_honest Vector storing the unique leaf ids of the tree relative to the honest sample.
#' @param y_honest Outcome vector of honest units.
#' @param honest_leaves Vector of size \code{n.samples}. The i-th element stores the id of the leaf where the i-th honest observation falls.
#'
honest_rpart_cpp <- function(unique_leaves_honest, y_honest, honest_leaves) {
    .Call('_aggTrees_honest_rpart_cpp', PACKAGE = 'aggTrees', unique_leaves_honest, y_honest, honest_leaves)
}

